[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app.js"
  status = 200

[build.environment]
  NODE_ENV = "development"

[functions]
  external_node_modules = ["express", "dotenv", "serverless-http", "cookie-parser", "cors", "helmet", "mongoose"]