[build]
  functions = "netlify/functions"
  command = "npm install"

[functions]
  external_node_modules = [
    "express",
    "dotenv",
    "serverless-http",
    "cookie-parser",
    "cors",
    "helmet",
    "mongoose",
    "axios",
    "bcrypt",
    "jsonwebtoken",
    "qrcode",
    "winston"
  ]

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app"
  status = 200
